//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class METRIC
    {
        public string SESSION_ID { get; set; }
        public string TIME { get; set; }
        public string USERNAME { get; set; }
        public string TIME_LOGGED_IN { get; set; }
        public string TIME_LOGGED_OUT { get; set; }
        public string NUMBER_OF_PAGE_VIEWS { get; set; }
        public string SESSIONDURATION { get; set; }
    
        public virtual TIME TIME1 { get; set; }
        public virtual USER USER { get; set; }
    }
}
