//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGE
    {
        public string TIME { get; set; }
        public string PAGE_TITLE { get; set; }
        public string USER { get; set; }
    
        public virtual TIME TIME1 { get; set; }
        public virtual USER USER1 { get; set; }
    }
}
